# Generated by Django 2.1.5 on 2019-05-14 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20190514_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='org_address',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Адрес местоположения организации'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='org_email',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Адрес электронной почты'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='org_full_name',
            field=models.CharField(blank=True, default=None, max_length=300, null=True, verbose_name='Полное название организации'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='org_header_emails',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Адреса электронной почты (для хедера)'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='org_header_phones',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Телефоны (для хедера)'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='org_intro',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Текст для главной страницы'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='org_phones',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Телефоны'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='org_short_name',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Краткое название организации'),
        ),
    ]
