# Generated by Django 2.1.5 on 2019-05-14 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_document_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='org_ac_codes',
        ),
        migrations.AddField(
            model_name='profile',
            name='org_acsm_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='шифр АЦСМ (необязательно)'),
        ),
        migrations.AddField(
            model_name='profile',
            name='org_acso_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='шифр АЦСО (необязательно)'),
        ),
        migrations.AddField(
            model_name='profile',
            name='org_acsp_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='шифр АЦСП (необязательно)'),
        ),
        migrations.AddField(
            model_name='profile',
            name='org_acst_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='шифр АЦСТ (необязательно)'),
        ),
        migrations.AddField(
            model_name='profile',
            name='org_cok_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='шифр АЦСТ (необязательно)'),
        ),
        migrations.AddField(
            model_name='profile',
            name='org_csp_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='шифр ЦСП (необязательно)'),
        ),
    ]
