# Generated by Django 2.1.5 on 2019-05-15 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_profile_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='org_acsm_reestr_link',
            field=models.URLField(default='naks.ru', verbose_name='Ссылка на реестр АЦСМ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='org_acso_reestr_link',
            field=models.URLField(default='naks.ru', verbose_name='Ссылка на реестр АЦСО'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='org_acsp_reestr_link',
            field=models.URLField(default='naks.ru', verbose_name='Ссылка на реестр АЦСП'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='org_acst_reestr_link',
            field=models.URLField(default='naks.ru', verbose_name='Ссылка на реестр АЦСМ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='org_cok_reestr_link',
            field=models.URLField(default='naks.ru', verbose_name='Ссылка на реестр ЦОК'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='org_csp_reestr_link',
            field=models.URLField(default='naks.ru', verbose_name='Ссылка на реестр ЦСП'),
            preserve_default=False,
        ),
    ]
