# Generated by Django 2.1.5 on 2019-05-15 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_auto_20190515_0843'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='org_logotype',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='upload/', verbose_name='Логотип организации'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='org_acst_reestr_link',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на реестр АЦСТ'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='org_cok_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='шифр ЦОК (необязательно)'),
        ),
    ]
