# Generated by Django 2.1.5 on 2019-05-15 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_auto_20190515_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='org_secondary_phone',
            field=models.CharField(blank=True, default=None, max_length=30, null=True, verbose_name='Второй телефон организации (используется в хедере)'),
        ),
        migrations.AddField(
            model_name='profile',
            name='org_secondary_phone_text',
            field=models.CharField(blank=True, default=None, max_length=30, null=True, verbose_name='Подпись под вторым телефоном в хедере, например "Бухгалтерия"'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='org_main_phone',
            field=models.CharField(blank=True, default=None, max_length=30, null=True, verbose_name='Главный телефон организации (используется в хедере)'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='org_main_phone_text',
            field=models.CharField(blank=True, default=None, max_length=30, null=True, verbose_name='Подпись под телефоном в хедере, например "Многоканальный"'),
        ),
    ]
