# Generated by Django 2.1.5 on 2019-05-15 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0018_auto_20190515_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='org_address_map_link',
            field=models.URLField(blank=True, default=None, null=True, verbose_name='Ссылка на карту'),
        ),
    ]
