# Generated by Django 2.1.5 on 2019-05-16 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0020_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='number',
            field=models.SmallIntegerField(blank=True, default=None, null=True, verbose_name='Порядок сортировки'),
        ),
    ]
