# Generated by Django 2.1.5 on 2019-05-16 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0021_service_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attestat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='Название аттестата(сертификата)')),
                ('image', models.ImageField(upload_to='upload/', verbose_name='Скан аттестата')),
                ('number', models.SmallIntegerField(verbose_name='Порядок сортировки')),
            ],
            options={
                'verbose_name_plural': 'Аттестаты соответствия',
                'verbose_name': 'Аттестат соответствия',
            },
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(help_text='\n            При добавлении услуги в этот раздел автоматически\n            будет создан пункт меню в разделе "Услуги", в котором они\n            сортируются в соответствии с порядком сортировки\n        ', max_length=64, verbose_name='Название услуги'),
        ),
    ]
