# Generated by Django 2.1.5 on 2019-05-24 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0022_auto_20190516_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='description',
            field=models.CharField(default='description', max_length=100, verbose_name='Краткое описание'),
            preserve_default=False,
        ),
    ]
